services:
  - type: web
    name: daily-expense-backend
    env: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    plan: free
    region: singapore
    healthCheckPath: /api/categories
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        fromConfigVar: APP_KEY # Sẽ được lấy từ Dashboard Render
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromConfigVar: DB_HOST
      - key: DB_PORT
        fromConfigVar: DB_PORT
      - key: DB_DATABASE
        fromConfigVar: DB_NAME
      - key: DB_USERNAME
        fromConfigVar: DB_USER
      - key: DB_PASSWORD
        fromConfigVar: DB_PASSWORD
      - key: CLOUDINARY_API_KEY
        fromConfigVar: CLOUDINARY_API_KEY
      - key: CLOUDINARY_API_SECRET
        fromConfigVar: CLOUDINARY_API_SECRET
      - key: CLOUDINARY_CLOUD_NAME
        fromConfigVar: CLOUDINARY_CLOUD_NAME
